### ISSUE TITLE
Unclear what "any project in mind?" box is for

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/design#1]
In https://w3c.github.io/design/projects/w3c-developers/get-involved/open-source there is an input box with a placeholder text of "any project in mind?"; it wasn't clear to me what this box was for. It might be a search box, a suggestion box, a messaging box.

**Comment by tripu** [comment]
It's a search (filter) box, I believe. But I agree, it's not obvious at first sight.

**Comment by gbaudusseau** [comment]
It's a search box yes. (to search a specific project) What about: 
- "search a project by name"
- "find a project"

**Comment by tripu** [comment]
@guibbs, I'd use &ldquo;search&rdquo; if it's going to go to the server and actually search and take a little while; and &ldquo;filter&rdquo; if it's going to shorten the list of projects on the fly, as you type.

Either way, I think a label outside the text input would be more usable than that (dim) prompt.

**Comment by gbaudusseau** [comment]
Should I get all the projects when the page load or should I request only 4,5 projects and then use the "load more projects" to request more button?

**Comment by tripu** [comment]
I'd say dump them all, @guibbs. It'd speed up the experience for the visitor (no need for further requests). If the number of projects becomes unmanageable, we can always paginate and/or filter on the client.

**Comment by tripu** [comment]
That page, afaik, is abandoned (now archived). Closing the issue.
