### ISSUE TITLE
W3C CG logo overlapping text

### ISSUE THREAD

**Issue by koalie** [w3c/design#11]
Feedback from @marcoscaceres about the sideways CG logos specially on mobile:
<img width="422" alt="screenshot 2017-11-21 09 14 51" src="https://user-images.githubusercontent.com/3716853/33044758-6d859318-ce4a-11e7-8195-961e4f9c473f.png">

**Comment by tripu** [comment]
Looks like a bug/oversight in all 4 stylesheets of the form
`https://www.w3.org/StyleSheets/TR/2016/{b,c}g-{draft,final}.css`;
I'll submit a patch.

**Comment by tripu** [comment]
It will be effectively closed when we deploy in production the current bunch of changes in tr-design.
